In [36]:
from IPython.display import display
import pandas as pd

standardized_data = pd.read_csv("standardized-kaggle-train-data.csv")
standardized_data.head()

Unnamed: 0        Id  MSSubClass   LotArea  OverallQual  OverallCond  \
0           0 -1.730865    0.073375 -0.207142     0.651479    -0.517200   
1           1 -1.728492   -0.872563 -0.091886    -0.071836     2.179628   
2           2 -1.726120    0.073375  0.073480     0.651479    -0.517200   
3           3 -1.723747    0.309859 -0.096897     0.651479    -0.517200   
4           4 -1.721374    0.073375  0.375148     1.374795    -0.517200   

   YearBuilt  YearRemodAdd  BsmtFinSF1  BsmtUnfSF  ...  BedroomAbvGr  \
0   1.050994      0.878668    0.575425  -0.944591  ...      0.163779   
1   0.156734     -0.429577    1.171992  -0.641228  ...      0.163779   
2   0.984752      0.830215    0.092907  -0.301643  ...      0.163779   
3  -1.863632     -0.720298   -0.499274  -0.061670  ...      0.163779   
4   0.951632      0.733308    0.463568  -0.174865  ...      1.390023   

   KitchenAbvGr  TotRmsAbvGrd  Fireplaces  GarageCars  GarageArea  WoodDeckSF  \
0     -0.211454      0.912210   -0.951226    0.311725    0.351000   -0.752176   
1     -0.211454     -0.318683    0.600495    0.311725   -0.060731    1.626195   
2     -0.211454     -0.318683    0.600495    0.311725    0.631726   -0.752176   
3     -0.211454      0.296763    0.600495    1.650307    0.790804   -0.752176   
4     -0.211454      1.527656    0.600495    1.650307    1.698485    0.780197   

   OpenPorchSF  EnclosedPorch  SalePrice  
0     0.216503      -0.359325   0.347273  
1    -0.704483      -0.359325   0.007288  
2    -0.070361      -0.359325   0.536154  
3    -0.176048       4.092524  -0.515281  
4     0.563760      -0.359325   0.869843  

[5 rows x 27 columns]

In [37]:
row_count = len(standardized_data.index)
print(f"The dataset has {row_count} rows")

standardized_data2 = standardized_data.drop(columns = ["Unnamed: 0", "Id"])
display(standardized_data2.head())

all_columns = list(standardized_data2.columns)
print(all_columns)
print(all_columns[-1])
print(all_columns[:-1])

The dataset has 1460 rows


MSSubClass   LotArea  OverallQual  OverallCond  YearBuilt  YearRemodAdd  \
0    0.073375 -0.207142     0.651479    -0.517200   1.050994      0.878668   
1   -0.872563 -0.091886    -0.071836     2.179628   0.156734     -0.429577   
2    0.073375  0.073480     0.651479    -0.517200   0.984752      0.830215   
3    0.309859 -0.096897     0.651479    -0.517200  -1.863632     -0.720298   
4    0.073375  0.375148     1.374795    -0.517200   0.951632      0.733308   

   BsmtFinSF1  BsmtUnfSF  TotalBsmtSF  1stFlrSF  ...  BedroomAbvGr  \
0    0.575425  -0.944591    -0.459303 -0.793434  ...      0.163779   
1    1.171992  -0.641228     0.466465  0.257140  ...      0.163779   
2    0.092907  -0.301643    -0.313369 -0.627826  ...      0.163779   
3   -0.499274  -0.061670    -0.687324 -0.521734  ...      0.163779   
4    0.463568  -0.174865     0.199680 -0.045611  ...      1.390023   

   KitchenAbvGr  TotRmsAbvGrd  Fireplaces  GarageCars  GarageArea  WoodDeckSF  \
0     -0.211454      0.912210   -0.951226    0.311725    0.351000   -0.752176   
1     -0.211454     -0.318683    0.600495    0.311725   -0.060731    1.626195   
2     -0.211454     -0.318683    0.600495    0.311725    0.631726   -0.752176   
3     -0.211454      0.296763    0.600495    1.650307    0.790804   -0.752176   
4     -0.211454      1.527656    0.600495    1.650307    1.698485    0.780197   

   OpenPorchSF  EnclosedPorch  SalePrice  
0     0.216503      -0.359325   0.347273  
1    -0.704483      -0.359325   0.007288  
2    -0.070361      -0.359325   0.536154  
3    -0.176048       4.092524  -0.515281  
4     0.563760      -0.359325   0.869843  

[5 rows x 25 columns]

['MSSubClass', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'BsmtFinSF1', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'GrLivArea', 'BsmtFullBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', 'SalePrice']
SalePrice
['MSSubClass', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'BsmtFinSF1', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'GrLivArea', 'BsmtFullBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch']


# Get the data into tensors

In [38]:
output_columns = [all_columns[-1]]
input_columns = all_columns[:-1]

data_frame = standardized_data2.copy(deep = True)

inputs_array = data_frame[input_columns].to_numpy()
targets_array = data_frame[output_columns].to_numpy()

In [39]:
import torch

device = "cpu"
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"

print(f"Using device {device}")

inputs = torch.Tensor(inputs_array).to(device)
targets = torch.Tensor(targets_array).to(device)

print(inputs.shape)
print(targets.shape)

Using device cuda
torch.Size([1460, 24])
torch.Size([1460, 1])


# Split the data between training and validation sets

In [40]:
from torch.utils.data import DataLoader, TensorDataset, random_split

dataset = TensorDataset(inputs, targets)

validation_percent = 0.3
validation_size = int(row_count * validation_percent)
training_size = row_count - validation_size

training_dataset, validation_dataset = random_split(dataset, [training_size, validation_size])
training_size, validation_size

(1022, 438)

In [41]:
batch_size = 16

training_loader = DataLoader(training_dataset, batch_size, shuffle = True)
validation_loader = DataLoader(validation_dataset, batch_size)

for X, y in training_loader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

Shape of X [N, C, H, W]: torch.Size([16, 24])
Shape of y: torch.Size([16, 1]) torch.float32


# Create the model

In [44]:
from torch import nn

input_size = len(input_columns)
output_size = len(output_columns)

class LinearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(input_size, output_size)

    def forward(self, x):
        output = self.linear(x)
        return output

    def training_step(self, batch):
        inputs, targets = batch
        output = self(inputs)
        loss = nn.functional.l1_loss(
            input = output,
            target = targets,
            size_average = None,
            reduce = None,
            reduction = 'mean'
        )
        return loss

    def validation_step(self, batch):
        inputs, targets = batch
        output = self(inputs)
        loss = nn.functional.l1_loss(
            input = output,
            target = targets,
            size_average = None,
            reduce = None,
            reduction = 'mean'
        )
        return {'val_loss': loss.detach()}

    def validation_epoch_end(self, outputs):
        batch_losses = [x['val_loss'] for x in outputs]
        epoch_loss = torch.stack(batch_losses).mean()
        return {'val_loss': epoch_loss.item()}

    def epoch_end(self, epoch, result, num_epochs):
        if(epoch) % 10 == 0 or epoch == num_epochs - 1:
            print(f"Epoch {epoch}, val_loss: {result['val_loss']:.4f}")

model = LinearRegression().to(device)
print(model)

LinearRegression(
  (linear): Linear(in_features=24, out_features=1, bias=True)
)


In [45]:
def evaluate(model, validation_loader):
    outputs = [model.validation_step(batch) for batch in validation_loader]
    return model.validation_epoch_end(outputs)

def fit( epochs, lr, model, training_loader, validation_loader, optimizer_function = torch.optim.SGD):
    history = []
    optimizer = optimizer_function(model.parameters(), lr)
    for epoch in range(epochs):
        for batch in training_loader:
            loss = model.training_step(batch)
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
        
        result = evaluate(model, validation_loader)
        model.epoch_end(epoch, result, epochs)
        history.append(result)
    
    return history

Loss before training

In [46]:
result = evaluate(model, validation_loader)
print(result)

{'val_loss': 0.6768202185630798}


# Do some training

In [61]:
epochs = 1000
lr = 1e-6
history = fit(epochs, lr, model, training_loader, validation_loader)

Epoch 0, val_loss: 0.2462
Epoch 10, val_loss: 0.2462
Epoch 20, val_loss: 0.2462
Epoch 30, val_loss: 0.2462
Epoch 40, val_loss: 0.2462
Epoch 50, val_loss: 0.2462
Epoch 60, val_loss: 0.2462
Epoch 70, val_loss: 0.2462
Epoch 80, val_loss: 0.2462
Epoch 90, val_loss: 0.2462
Epoch 100, val_loss: 0.2462
Epoch 110, val_loss: 0.2462
Epoch 120, val_loss: 0.2462
Epoch 130, val_loss: 0.2462
Epoch 140, val_loss: 0.2462
Epoch 150, val_loss: 0.2462
Epoch 160, val_loss: 0.2462
Epoch 170, val_loss: 0.2462
Epoch 180, val_loss: 0.2462
Epoch 190, val_loss: 0.2462
Epoch 200, val_loss: 0.2462
Epoch 210, val_loss: 0.2462
Epoch 220, val_loss: 0.2462
Epoch 230, val_loss: 0.2462
Epoch 240, val_loss: 0.2462
Epoch 250, val_loss: 0.2462
Epoch 260, val_loss: 0.2462
Epoch 270, val_loss: 0.2462
Epoch 280, val_loss: 0.2462
Epoch 290, val_loss: 0.2462
Epoch 300, val_loss: 0.2462
Epoch 310, val_loss: 0.2462
Epoch 320, val_loss: 0.2462
Epoch 330, val_loss: 0.2462
Epoch 340, val_loss: 0.2462
Epoch 350, val_loss: 0.2462
Epo

# Save the model

In [66]:
torch.save(model.state_dict(), "kaggle_predict_house_prices_model.pth")
print("Saved PyTorchModel State to kaggle_predict_house_prices_model.pth")

torch.save(model, "kaggle_predict_house_prices_model.pt")
print("Saved PyTorchModel to kaggle_predict_house_prices_model.pt")

Saved PyTorchModel State to kaggle_predict_house_prices_model.pth
Saved PyTorchModel to kaggle_predict_house_prices_model.pt


In [63]:
validation_dataset[0]

(tensor([ 0.7828, -0.3507, -0.7952, -0.5172,  0.2561, -0.2842, -0.9730, -1.2842,
         -2.4112,  0.9636, -0.7952,  0.0372, -0.8200,  0.7897, -0.7616,  1.3900,
          4.3286,  0.9122, -0.9512,  0.3117, -0.3415, -0.7522, -0.7045, -0.3593],
        device='cuda:0'),
 tensor([-0.7815], device='cuda:0'))

In [64]:
input, target = validation_dataset[0]
model(input)

tensor([-0.9417], device='cuda:0', grad_fn=<AddBackward0>)

In [65]:
target

tensor([-0.7815], device='cuda:0')